#!/usr/bin/env node
import { build } from 'esbuild'
import { fileURLToPath } from 'node:url'
import { resolve, dirname } from 'node:path'
import { readFile, writeFile } from 'node:fs/promises'
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const result = await build({ absWorkingDir: root, entryPoints: ['plugin/src/client.js'], bundle: true, platform: 'browser', format: 'iife', target: 'es2022', write: false, charset: 'utf8', loader: { '.css': 'text' }, legalComments: 'none', minify: false })
const output = '// Generated by scripts/build-client.mjs; edit plugin/src/client.js and sidebar.js instead.' + String.fromCharCode(10) + result.outputFiles[0].text
const target = resolve(root, 'plugin/client.js')
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== output) throw new Error('client.js is stale; run pnpm build:client')
  console.log('client.js matches its source')
} else {
  await writeFile(target, output)
  console.log('Built plugin/client.js (' + Buffer.byteLength(output) + ' bytes)')
}
